# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b555f761050cdf786e9fdb0a67ba903df42d4876619991c37f301665795aa72aaacd46f32046dc7766ce1bada87a7e892526d342ca23fb73ced0f6baca5d9546

test:
  secret_key_base: 5ad5336af4e3e781c896c8a47023b7dbde0a31e283db78c5674cad9fffdc1450b974d588a205cb681e470d4a2443af02cba582ec0f850766104360dc1e7f9cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
